---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: blue-myself
# description will be included in the image's metadata
description: A container workstation OS based around niri

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: akmods
    base: main
    install:
      - v4l2loopback

  - type: kargs
    kargs:
      - nvidia-drm.modeset=1
      - rd.driver.pre=nvidia
      - rd.driver.pre=nvidia_modeset
      - rd.driver.pre=nvidia_uvm
      - rd.driver.pre=nvidia_drm

  - type: dnf
    repos:
      copr:
        - atim/starship
        - yalter/niri
    install:
      packages:
        - niri
        - xdg-desktop-portal
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
        - gnome-keyring-pam
        - nautilus
        - waybar
        - greetd
        - greetd-gtkgreet
        - tuigreet
        - ptyxis
        - foot
        - fuzzel
        - starship
        - helix
        - ripgrep
        - jq
        - bat
        - fzf
        - dust
        - duf
        - fd
        - cheat
        - tealdeer
        - zoxide
        - nmap
#    remove:
#      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
 #       - firefox
 #       - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.brave.Browser
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: chezmoi
    repository: "https://github.com/latentdrift/dotfiles"
    all-users: true
    file-conflict-policy: skip

  # - type: fonts
  #   fonts:
  #     nerd-fonts:
  #       - CaskaydiaCove
  #       - FiraCode
  #       - GohuFont
  #       - Hack
  #       - Iosevka
  #       - IosevkaTerm
  #       - JetBrainsMono
  #       - Noto
  #       - OpenDyslexic
  #       - RobotoMono
  #       - SauceCodePro
  #       - Symbols
  #     google-fonts:
  #       - Roboto
  #       - Inter
  #       - Quicksand

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
